version: '3.8'
services:
    filecloud_hot:
        build: 
            context: ./services/filecloud_hot
            dockerfile: Dockerfile.dev
            args:
                - VOLUME_FILES=${VOLUME_FILES}
                - AWS_SHARED_CREDENTIALS_FILE=/home/app/filecloud_hot/${AWS_SHARED_CREDENTIALS_FILE}
        container_name: filecloud_hot-dev
        volumes:
            - filecloud_data:${VOLUME_FILES}:rw
        command: >
                gunicorn --bind 0.0.0.0:5000 manage:app
        expose:
            - 5000
        env_file:
            - ./.env.dev
        depends_on:
            - db
    filecloud_cold:
        build: 
            context: ./services/filecloud_cold
            dockerfile: Dockerfile.dev
            args:
                - VOLUME_FILES=${VOLUME_FILES}
                - AWS_SHARED_CREDENTIALS_FILE=/home/app/filecloud_cold/${AWS_SHARED_CREDENTIALS_FILE}
        container_name: filecloud_cold-dev
        volumes:
            - filecloud_data:${VOLUME_FILES}:rw
        command: >
                python3 manage.py
        expose:
            - 5000
        env_file:
            - ./.env.dev
        depends_on:
            - db
    db:
        build:
            context: ./services/postgres_dev
            dockerfile: db.Dockerfile
        container_name: filecloud-db-dev
        volumes:
            - postgres_data:/var/lib/postgresql/data/
        env_file: 
            - ./.env.dev.db
    nginx:
        build: ./services/nginx
        container_name: filecloud_hot-nginx-dev
        ports:
            - 1337:80
        depends_on:
            - filecloud_hot
volumes:
    filecloud_data: 
    postgres_data: